[tool.poetry]
name = "bank-repository"
version = "0.1.0"
description = ""
authors = ["quintenvanvelzen <quinten@dexterenergy.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
